Repository cvat-ai/cvat, pull requests merged in 2018-10, with the labels that each got.

#110 Environment steps have been added into CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#114 Incremental collection update now works with outside/keyframe (Critical)
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapes.js
Labels: bug

#112 Now we store virtual URL instead of update it in the browser address bar
  cvat/apps/engine/static/engine/js/annotationUI.js
  cvat/apps/engine/static/engine/js/base.js
  cvat/apps/engine/static/engine/js/player.js
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapeFilter.js
  cvat/apps/engine/static/engine/js/shapes.js
  cvat/apps/engine/templates/engine/annotation.html
  tests/eslintrc.conf.js
Labels: bug

#109 Bug has been fixed: label UIs don't update after changelabel
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapes.js
Labels: bug

#117 Shortcuts patch
  cvat/apps/engine/static/engine/js/annotationUI.js
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapeCreator.js
  cvat/apps/engine/static/engine/js/shapeGrouper.js
  cvat/apps/engine/static/engine/js/shapeMerger.js
  cvat/apps/engine/static/engine/js/userConfig.js
Labels: enhancement

#116 Switch hide/lock property for all object with specified label
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapes.js
  cvat/apps/engine/static/engine/stylesheet.css
Labels: enhancement

#119 Minor changes
  CHANGELOG.md
  cvat/apps/engine/static/engine/js/annotationUI.js
  cvat/apps/engine/static/engine/js/player.js
  cvat/apps/engine/static/engine/js/shapeCollection.js
Labels: documentation, enhancement

#127 Analytics v2
  analytics/docker-compose.yml
  analytics/elasticsearch/Dockerfile
  analytics/kibana/kibana.yml
  analytics/logstash/logstash.conf
  cvat/apps/documentation/static/documentation/js/shortcuts.js
  cvat/apps/engine/annotation.py
  cvat/apps/engine/log.py
  cvat/apps/engine/static/engine/js/userConfig.js
  cvat/apps/engine/task.py
  cvat/apps/engine/urls.py
  cvat/apps/engine/views.py
  cvat/apps/log_viewer/__init__.py
  cvat/apps/log_viewer/admin.py
  cvat/apps/log_viewer/apps.py
  cvat/apps/log_viewer/migrations/__init__.py
  cvat/apps/log_viewer/models.py
  cvat/apps/log_viewer/static/log_viewer/js/shortcuts.js
  cvat/apps/log_viewer/tests.py
  cvat/apps/log_viewer/urls.py
  cvat/apps/log_viewer/views.py
  cvat/apps/tf_annotation/views.py
  cvat/requirements/base.txt
  cvat/settings/base.py
  cvat/urls.py
  docker-compose.yml
Labels: enhancement

#129 Fix several problems with analytics
  cvat/apps/tf_annotation/views.py
  cvat/settings/base.py
  cvat/urls.py
  supervisord.conf
Labels: bug

#133 Bug fixed: client_idx is repeated for various labels
  cvat/apps/tf_annotation/views.py
Labels: bug

#134 OpenVino integration
  .gitignore
  CHANGELOG.md
  Dockerfile
  README.md
  components/README.md
  components/analytics/README.md
  components/analytics/docker-compose.analytics.yml
  components/analytics/elasticsearch/Dockerfile
  components/analytics/elasticsearch/elasticsearch.yml
  components/analytics/kibana/Dockerfile
  components/analytics/kibana/export.json
  components/analytics/kibana/kibana.yml
  components/analytics/kibana/setup.py
  components/analytics/logstash/Dockerfile
  components/analytics/logstash/logstash.conf
  components/cuda/README.md
  components/cuda/docker-compose.cuda.yml
  components/cuda/install.sh
  components/openvino/README.md
  components/openvino/docker-compose.openvino.yml
  components/openvino/eula.cfg
  components/openvino/install.sh
  components/tf_annotation/README.md
  components/tf_annotation/docker-compose.tf_annotation.yml
  components/tf_annotation/install.sh
  cvat/apps/tf_annotation/README.md
  cvat/apps/tf_annotation/requirements.txt
  cvat/apps/tf_annotation/views.py
Labels: enhancement

#138 Update main README.md
  README.md
Labels: documentation

#145 OpenVino doc was updated
  components/openvino/README.md
Labels: documentation

#148 OpenVino installation process now uses the included depedendencies file
  Dockerfile
  components/openvino/install.sh
Labels: bug

#153 Job status was implemented
  cvat/apps/engine/migrations/0012_auto_20181024_1817.py
  cvat/apps/engine/models.py
  cvat/apps/engine/static/engine/js/annotationUI.js
  cvat/apps/engine/task.py
  cvat/apps/engine/templates/engine/annotation.html
  cvat/apps/engine/urls.py
  cvat/apps/engine/views.py
Labels: enhancement

#156 Backlink to task
  cvat/apps/dashboard/__init__.py
  cvat/apps/dashboard/static/dashboard/js/enginePlugin.js
  cvat/apps/dashboard/templates/dashboard/task.html
  cvat/apps/dashboard/views.py
Labels: enhancement
