Repository cvat-ai/cvat, pull requests merged in 2018-09, with the labels that each got.

#45 Bug has been fixed: Failed to execute 'inverse' on 'SVGMatrix': The m…
  cvat/apps/engine/static/engine/js/annotationUI.js
Labels: bug

#46 Performance of frame changing has been increased due to UI containers…
  cvat/apps/engine/static/engine/base.css
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/stylesheet.css
  cvat/apps/engine/templates/engine/annotation.html
Labels: enhancement

#51 Data validation on client and server
  cvat/apps/engine/annotation.py
  cvat/apps/engine/static/engine/js/annotationParser.js
  cvat/apps/engine/static/engine/js/shapeBuffer.js
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapes.js
Labels: bug

#57 Polygon edit method
  cvat/apps/engine/static/engine/js/annotationUI.js
  cvat/apps/engine/static/engine/js/polyshapeEditor.js
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapeCreator.js
  cvat/apps/engine/static/engine/js/shapes.js
  cvat/apps/engine/templates/engine/annotation.html
  tests/eslintrc.conf.js
Labels: enhancement

#60 Big int migration file has been rewritten with Python syntax
  cvat/apps/engine/migrations/0009_auto_20180917_1424.py
  cvat/apps/engine/models.py
Labels: bug

#61 Some memory leaks have been fixed
  cvat/apps/engine/static/engine/js/3rdparty.patch
  cvat/apps/engine/static/engine/js/player.js
  cvat/apps/engine/static/engine/js/shapes.js
Labels: bug

#66 Player navigation has been fixed if window was scrolled
  cvat/apps/engine/static/engine/js/player.js
Labels: bug

#69 Contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#71 Cuda installation has been fixed
  cvat/apps/tf_annotation/docker_setup_tf_annotation.sh
Labels: bug

#73 CVAT links to specific frame or object/objects
  cvat/apps/engine/static/engine/js/annotationUI.js
  cvat/apps/engine/static/engine/js/base.js
  cvat/apps/engine/static/engine/js/player.js
  cvat/apps/engine/static/engine/js/polyshapeEditor.js
  cvat/apps/engine/static/engine/js/shapeCreator.js
  cvat/apps/engine/static/engine/js/shapeFilter.js
  tests/eslintrc.conf.js
Labels: enhancement

#75 Added gitter badge into README
  README.md
Labels: documentation

#77 Ability to change an opacity for selected shapes
  cvat/apps/engine/static/engine/js/base.js
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapeFilter.js
  cvat/apps/engine/static/engine/js/shapes.js
  cvat/apps/engine/templates/engine/annotation.html
Labels: enhancement

#79 Update README
  README.md
  cvat/apps/documentation/static/documentation/images/cvat.jpg
Labels: documentation

#82 Improve documentation for overlap parameter
  cvat/apps/documentation/user_guide.md
Labels: documentation

#81 Improve description how to specify labels with attributes.
  cvat/apps/documentation/user_guide.md
Labels: documentation

#85 Added the initial version of CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#88 Describe XML format v1.1
  cvat/apps/documentation/user_guide.md
  cvat/apps/documentation/xml_format.md
  cvat/apps/engine/annotation.py
Labels: documentation

#94 Develop changelog has been updated
  CHANGELOG.md
Labels: documentation

#97 Release 0.2 fix
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapes.js
Labels: bug

#99 Fixes from release 0.2
  cvat/apps/engine/static/engine/js/shapeCollection.js
  cvat/apps/engine/static/engine/js/shapes.js
Labels: bug

#98 Bug has been fixed: impossible to close points after editing
  cvat/apps/engine/static/engine/js/shapes.js
Labels: bug
