Repository cvat-ai/cvat, pull requests merged in 2020-03, with the labels that each got.

#1202 React UI: Pinned option was added
  cvat-canvas/src/typescript/canvasView.ts
  cvat-core/src/annotations-objects.js
  cvat-core/src/enums.js
  cvat-core/src/object-state.js
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
Labels: enhancement

#1227 React UI: batch of fixes
  cvat-canvas/src/typescript/canvas.ts
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/editHandler.ts
  cvat-core/src/annotations-objects.js
  cvat-core/src/object-state.js
  cvat-ui/src/cvat-canvas.ts
  cvat-ui/src/reducers/annotation-reducer.ts
Labels: bug

#1198 React UI: Added button to cancel started automatic annotation
  cvat-ui/src/actions/models-actions.ts
  cvat-ui/src/components/tasks-page/styles.scss
  cvat-ui/src/components/tasks-page/task-item.tsx
  cvat-ui/src/containers/actions-menu/actions-menu.tsx
  cvat-ui/src/containers/model-runner-dialog/model-runner-dialog.tsx
  cvat-ui/src/containers/tasks-page/task-item.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/models-reducer.ts
  cvat-ui/src/reducers/notifications-reducer.ts
Labels: enhancement

#1230 React UI: Added shortcuts
  cvat-canvas/src/typescript/drawHandler.ts
  cvat-core/src/annotations-collection.js
  cvat-core/src/session.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/actions/shortcuts-actions.ts
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
  cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/shortcuts-dialog/shortcuts-dialog.tsx
  cvat-ui/src/containers/annotation-page/annotation-page.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/label-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/labels-list.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/index.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/notifications-reducer.ts
  cvat-ui/src/reducers/root-reducer.ts
  cvat-ui/src/reducers/shortcuts-reducer.ts
Labels: enhancement

#1255 React UI: Attribute annotation mode
  cvat-canvas/src/typescript/canvasView.ts
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/components/annotation-page/annotations-filters-input.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-editor.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-switcher.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-basics-edtior.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-switcher.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-workspace.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list-header.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
  cvat-ui/src/components/annotation-page/standard-workspace/standard-workspace.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
  cvat-ui/src/components/annotation-page/styles.scss
  cvat-ui/src/components/annotation-page/top-bar/right-group.tsx
  cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/components/settings-page/workspace-settings.tsx
  cvat-ui/src/containers/annotation-page/annotation-page.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/label-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/interfaces.ts
Labels: enhancement

#1288 React UI: Added logging
  cvat-canvas/README.md
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/drawHandler.ts
  cvat-canvas/src/typescript/mergeHandler.ts
  cvat-core/src/api.js
  cvat-core/src/config.js
  cvat-core/src/enums.js
  cvat-core/src/log.js
  cvat-core/src/logger-storage.js
  cvat-core/src/logging.js
  cvat-core/src/server-proxy.js
  cvat-core/src/session.js
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/containers/annotation-page/annotation-page.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/cvat-logger.ts
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/notifications-reducer.ts
  cvat-ui/webpack.config.js
Labels: enhancement

#1297 React UI: Better exception handling
  cvat-core/package.json
  cvat-core/src/enums.js
  cvat-core/src/log.js
  cvat-core/src/logger-storage.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/actions/boundaries-actions.ts
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/global-error-boundary/global-error-boundary.tsx
  cvat-ui/src/components/global-error-boundary/styles.scss
  cvat-ui/src/index.tsx
  cvat-ui/src/reducers/about-reducer.ts
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/auth-reducer.ts
  cvat-ui/src/reducers/formats-reducer.ts
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/models-reducer.ts
  cvat-ui/src/reducers/notifications-reducer.ts
  cvat-ui/src/reducers/settings-reducer.ts
  cvat-ui/src/reducers/share-reducer.ts
  cvat-ui/src/reducers/shortcuts-reducer.ts
  cvat-ui/src/reducers/tasks-reducer.ts
  cvat-ui/src/reducers/users-reducer.ts
  cvat-ui/src/utils/redux.ts
Labels: enhancement

#1314 React UI: Batch of fixes
  cvat-canvas/src/typescript/editHandler.ts
  cvat-core/src/annotations-collection.js
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-editor.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/propagate-confirm.tsx
  cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
  cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/components/settings-page/player-settings.tsx
  cvat-ui/src/components/settings-page/workspace-settings.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/propagate-confirm.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/utils/math.ts
Labels: bug

#1318 React UI: Batch of fixes
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/svg.patch.ts
  cvat-core/src/annotations-collection.js
  cvat-core/src/annotations-history.js
  cvat-core/src/annotations-objects.js
  cvat-core/src/object-state.js
  cvat-core/src/session.js
  cvat-core/tests/api/annotations.js
  cvat-core/tests/api/object-state.js
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/labels-editor/common.ts
  cvat-ui/src/components/labels-editor/label-form.tsx
  cvat-ui/src/components/labels-editor/labels-editor.tsx
  cvat-ui/src/containers/annotation-page/annotation-page.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/interfaces.ts
Labels: bug

#1330 Fix known hosts issue in Git app
  Dockerfile
Labels: bug

#1323 React UI: Added titles
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-switcher.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-switcher.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/cursor-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-points-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polygon-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polyline-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-rectangle-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/fit-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/group-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/merge-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/move-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/resize-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/rotate-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-popover.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/split-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list-header.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
  cvat-ui/src/components/annotation-page/top-bar/annotation-menu.tsx
  cvat-ui/src/components/annotation-page/top-bar/left-group.tsx
  cvat-ui/src/components/annotation-page/top-bar/player-buttons.tsx
  cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
  cvat-ui/src/components/annotation-page/top-bar/right-group.tsx
  cvat-ui/src/components/annotation-page/top-bar/statistics-modal.tsx
  cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/header/header.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/setup-tag-popover.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/containers/header/header.tsx
  cvat-ui/src/index.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/shortcuts-reducer.ts
Labels: bug, enhancement

#1332 Fixed zOrder range computing in case when there are tags
  cvat-ui/src/actions/annotation-actions.ts
Labels: bug
