Repository cvat-ai/cvat, pull requests merged in 2020-12, with the labels that each got.

#2513 Update README.md
  README.md
Labels: documentation

#2338 Simple Review Pipeline (Server)
  cvat/apps/authentication/auth.py
  cvat/apps/documentation/AWS-Deployment-Guide.md
  cvat/apps/engine/migrations/0034_auto_20201125_1426.py
  cvat/apps/engine/models.py
  cvat/apps/engine/serializers.py
  cvat/apps/engine/signals.py
  cvat/apps/engine/tests/test_rest_api.py
  cvat/apps/engine/urls.py
  cvat/apps/engine/views.py
Labels: enhancement

#2506 Disabled ability to edit positions in attribute annotation mode
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/canvasView.ts
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx
Labels: bug, need test

#2517 Fixed: TypeError: Cannot read property 'toString' of undefined
  CHANGELOG.md
  cvat-ui/src/actions/annotation-actions.ts
Labels: bug, need test

#2507 Fixed grouping when press escape with drawn region or change a frame
  CHANGELOG.md
  cvat-canvas/src/typescript/groupHandler.ts
  cvat-ui/package-lock.json
  cvat-ui/package.json
Labels: bug, need test

#2509 Added dedicated component for label selection, added tooltip
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-popover.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-basics.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/tag-annotation-sidebar.tsx
  cvat-ui/src/components/label-selector/label-selector.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/setup-tag-popover.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
Labels: enhancement

#2525 Reset state after logout & changing a job
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/reducers/review-reducer.ts
Labels: bug

#2527 Redirect query param
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/login-with-token/login-with-token.tsx
  cvat-ui/src/reducers/auth-reducer.ts
  tests/cypress/support/commands.js
Labels: need test

#2544 Fixed: TypeError: Cannot read property 'id' of undefined
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/projects-actions.ts
  cvat-ui/src/actions/review-actions.ts
  cvat-ui/src/actions/tasks-actions.ts
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/components/projects-page/project-list.tsx
  cvat-ui/src/components/task-page/task-page.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/review-reducer.ts
  cvat-ui/src/reducers/tasks-reducer.ts
Labels: bug

#2561 Antd4 migration minor fixes found on cvat.org
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-side-bar.tsx
  cvat-ui/src/components/projects-page/project-list.tsx
  cvat-ui/src/components/task-page/job-list.tsx
  cvat-ui/src/components/tasks-page/task-item.tsx
  cvat-ui/src/components/tasks-page/task-list.tsx
Labels: bug

#2626 Fixed project removing
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/project-page/top-bar.tsx
Labels: bug
