Repository cvat-ai/cvat, pull requests merged in 2020-07, with the labels that each got.

#1820 [CVAT-UI]: Appearance settings in AAM, keyframe navigation and other buttons in AAM
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/appearance-block.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-editor.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-basics-edtior.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/appearance-block.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-attribute.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-basics.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-buttons.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-details.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-menu.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/standard-workspace.tsx
  cvat-ui/src/components/global-error-boundary/global-error-boundary.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-buttons.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-side-bar.tsx
  cvat-ui/src/containers/create-model-page/create-model-page.tsx
  cvat-ui/src/containers/create-task-page/create-task-page.tsx
  cvat-ui/src/containers/header/header.tsx
  cvat-ui/src/containers/model-runner-dialog/model-runner-dialog.tsx
  cvat-ui/src/containers/task-page/task-page.tsx
  cvat-ui/src/containers/tasks-page/tasks-page.tsx
  cvat-ui/src/utils/redux.ts
Labels: enhancement

#1834 [CVAT-UI] Fixed displaying on canvas in some cases
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/canvasView.ts
Labels: bug

#1874 [CVAT-UI] Critical fixes
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/canvas.ts
  cvat-canvas/src/typescript/canvasModel.ts
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/groupHandler.ts
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-attribute.tsx
  cvat-ui/src/containers/annotation-page/annotation-page.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/utils/redux.ts
Labels: bug

#1881 Windows 10 guide
  CONTRIBUTING.md
  cvat/apps/documentation/installation.md
Labels: documentation

#1904 Image quality parameter mismatch #1900
  CHANGELOG.md
  cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx
  cvat/apps/documentation/user_guide.md
Labels: enhancement

#1892 CVAT-UI: Couple of fixes
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/autoborderHandler.ts
  cvat-canvas/src/typescript/drawHandler.ts
  cvat-canvas/src/typescript/editHandler.ts
  cvat-core/package.json
  cvat-core/src/annotations-objects.js
  cvat/apps/dataset_manager/annotation.py
Labels: bug

#1877 Smaller object details
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-attribute.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
Labels: enhancement

#1921 Intelligent polygon editing
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/editHandler.ts
Labels: enhancement

#1935 Fixed default undefined, fixed double change
  cvat-core/package.json
  cvat-core/src/annotations-objects.js
  cvat-core/src/api.js
  cvat-core/src/enums.js
  cvat-core/src/object-state.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
Labels: bug

#1966 [React UI] A couple of fixes
  CHANGELOG.md
  cvat-core/package.json
  cvat-core/src/frames.js
  cvat-core/src/session.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/plugins-actions.ts
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/notifications-reducer.ts
Labels: bug
