Repository cvat-ai/cvat, pull requests merged in 2020-06, with the labels that each got.

#1683 [React] Added shortcuts & ability to search a label
  CHANGELOG.md
  CONTRIBUTING.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/split-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/color-changer.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/label-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/label-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/reducers/shortcuts-reducer.ts
Labels: enhancement

#1727 [CVAT-UI] Better labels validation and fixed React warning
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/labels-editor/common.ts
  cvat-ui/src/components/labels-editor/raw-viewer.tsx
Labels: bug

#1755 [CVAT-UI] Fixed AAM bug: #1750
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
Labels: bug

#1571 Interpolation of polyshapes in CVAT
  CHANGELOG.md
  cvat-canvas/README.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/scss/canvas.scss
  cvat-canvas/src/typescript/canvas.ts
  cvat-canvas/src/typescript/canvasModel.ts
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/consts.ts
  cvat-canvas/src/typescript/drawHandler.ts
  cvat-canvas/src/typescript/editHandler.ts
  cvat-canvas/src/typescript/shared.ts
  cvat-canvas/src/typescript/svg.patch.ts
  cvat-core/docs/Interpolation.pdf
  cvat-core/package.json
  cvat-core/src/annotations-objects.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-point-context-menu.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/standard-workspace.tsx
  cvat-ui/src/components/annotation-page/styles.scss
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/canvas-point-context-menu.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/cvat-canvas-wrapper.ts
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/shortcuts-reducer.ts
  cvat/apps/dataset_manager/annotation.py
Labels: enhancement

#1766 Stylelint SCSS linter
  .stylelintrc.json
  CHANGELOG.md
  CONTRIBUTING.md
  cvat-canvas/src/scss/canvas.scss
  cvat-ui/src/base.scss
  cvat-ui/src/components/actions-menu/styles.scss
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
  cvat-ui/src/components/annotation-page/styles.scss
  cvat-ui/src/components/feedback/styles.scss
  cvat-ui/src/components/global-error-boundary/styles.scss
  cvat-ui/src/components/header/styles.scss
  cvat-ui/src/components/labels-editor/styles.scss
  cvat-ui/src/components/register-page/styles.scss
  cvat-ui/src/components/settings-page/styles.scss
  cvat-ui/src/components/task-page/styles.scss
  cvat-ui/src/components/tasks-page/styles.scss
  package.json
Labels: enhancement

#1800 Bug fixes: Propagation from the latest frame, number attribute validation
  CHANGELOG.md
  cvat-core/package.json
  cvat-core/src/annotations-collection.js
  cvat-core/src/annotations-objects.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/labels-editor/label-form.tsx
Labels: bug

#1705 CVAT UI: batch of fixes
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/scss/canvas.scss
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/shared.ts
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/auth-actions.ts
  cvat-ui/src/actions/settings-actions.ts
  cvat-ui/src/actions/useragreements-actions.ts
  cvat-ui/src/components/actions-menu/dump-submenu.tsx
  cvat-ui/src/components/actions-menu/export-submenu.tsx
  cvat-ui/src/components/actions-menu/load-submenu.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-cuboid-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/header/header.tsx
  cvat-ui/src/components/header/settings-modal/player-settings.tsx
  cvat-ui/src/components/header/settings-modal/settings-modal.tsx
  cvat-ui/src/components/header/settings-modal/styles.scss
  cvat-ui/src/components/header/settings-modal/workspace-settings.tsx
  cvat-ui/src/components/login-page/cookie-policy-drawer.tsx
  cvat-ui/src/components/register-page/register-page.tsx
  cvat-ui/src/components/settings-page/settings-page.tsx
  cvat-ui/src/components/task-page/details.tsx
  cvat-ui/src/components/tasks-page/task-item.tsx
  cvat-ui/src/consts.ts
  cvat-ui/src/containers/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-side-bar.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/containers/header/header.tsx
  cvat-ui/src/containers/header/settings-modal/player-settings.tsx
  cvat-ui/src/containers/header/settings-modal/workspace-settings.tsx
  cvat-ui/src/containers/register-page/register-page.tsx
  cvat-ui/src/containers/settings-page/settings-page.tsx
  cvat-ui/src/containers/tasks-page/task-item.tsx
  cvat-ui/src/index.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/notifications-reducer.ts
  cvat-ui/src/reducers/settings-reducer.ts
  cvat-ui/src/reducers/shortcuts-reducer.ts
  cvat-ui/src/utils/enviroment.ts
  cvat-ui/src/utils/math.ts
Labels: enhancement

#1753 [CVAT-UI] Data annotation team requests and some fixes
  CHANGELOG.md
  cvat-core/package.json
  cvat-core/src/annotations.js
  cvat-core/src/session.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/base.scss
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
  cvat-ui/src/components/header/settings-modal/styles.scss
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
Labels: bug, enhancement

#1570 CVAT UI: tag annotation workspace
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/styles.scss
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/shortcuts-select.tsx
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/tag-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-workspace.tsx
  cvat-ui/src/components/annotation-page/top-bar/right-group.tsx
  cvat-ui/src/reducers/interfaces.ts
Labels: enhancement
