Repository cvat-ai/cvat, pull requests merged in 2020-09, with the labels that each got.

#2102 Running detectors on the fly
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
  cvat-ui/src/components/model-runner-modal/detector-runner.tsx
  cvat-ui/src/components/model-runner-modal/model-runner-dialog.tsx
  cvat-ui/src/components/model-runner-modal/model-runner-modal.tsx
  cvat-ui/src/components/model-runner-modal/styles.scss
  cvat-ui/src/components/task-page/task-page.tsx
  cvat-ui/src/components/tasks-page/task-list.tsx
  cvat-ui/src/containers/model-runner-dialog/model-runner-dialog.tsx
  cvat-ui/src/styles.scss
Labels: enhancement

#2151 Fix CVAT format import for frame stepped tasks
  CHANGELOG.md
  cvat/apps/dataset_manager/formats/cvat.py
  cvat/apps/engine/tests/_test_rest_api.py
Labels: bug

#2136 UI Tracking with serverless functions
  CHANGELOG.md
  cvat-canvas/src/typescript/interactionHandler.ts
  cvat-core/package-lock.json
  cvat-core/package.json
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/actions/plugins-actions.ts
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-basics.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-menu.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/standard-workspace.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/utils/range.ts
Labels: enhancement, need test

#2148 Added automatic annotation progress to the task view
  CHANGELOG.md
  cvat-ui/src/components/task-page/details.tsx
  cvat-ui/src/components/tasks-page/automatic-annotation-progress.tsx
  cvat-ui/src/components/tasks-page/task-item.tsx
  cvat-ui/src/containers/task-page/details.tsx
Labels: enhancement

#2162 Using serverside paremeter min_pos_points, right colors of labels in …
  CHANGELOG.md
  cvat-core/package-lock.json
  cvat-core/package.json
  cvat-core/src/lambda-manager.js
  cvat-core/src/ml-model.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
  cvat-ui/src/components/model-runner-modal/detector-runner.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat/apps/lambda_manager/views.py
Labels: enhancement

#2172 Prevent CVAT failure when web analytics is failure
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/utils/enviroment.ts
Labels: bug

#2204 Using "alt" instead of "ctrl" to delete a point, fixed reducer
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/svg.patch.ts
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/canvas-point-context-menu.tsx
  cvat-ui/src/reducers/models-reducer.ts
Labels: bug

#2203 Fixed two issues #2053 and #2202
  CHANGELOG.md
  cvat-core/package-lock.json
  cvat-core/package.json
  cvat-core/src/log.js
  cvat-core/src/logger-storage.js
  cvat-ui/src/actions/annotation-actions.ts
Labels: bug, need test

#2210 Updated high volnurabilities from dependabot & npm audit
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-ui/package-lock.json
  cvat-ui/package.json
Labels: dependencies

#2199 Fixed failure after updating a label on cvat.org
  cvat-core/src/server-proxy.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/tasks-actions.ts
  cvat-ui/src/components/labels-editor/constructor-updater.tsx
  cvat-ui/src/components/labels-editor/label-form.tsx
  cvat-ui/src/components/labels-editor/labels-editor.tsx
  cvat-ui/src/components/labels-editor/raw-viewer.tsx
  cvat-ui/src/components/task-page/task-page.tsx
  cvat-ui/src/containers/task-page/details.tsx
  cvat-ui/src/containers/task-page/task-page.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/tasks-reducer.ts
Labels: bug

#2220 Additional code has been added to investigate exception
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
Labels: bug
