Repository cvat-ai/cvat, pull requests merged in 2021-03, with the labels that each got.

#2880 Added simple extra popover to keep other controls out of display
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/control-visibility-observer.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/cursor-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-cuboid-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-points-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polygon-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polyline-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-rectangle-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/fit-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/group-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/merge-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/move-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/resize-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/rotate-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/split-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
Labels: bug

#2868 Fixed: cannot close some issues
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/review/hidden-issue-label.tsx
Labels: bug

#2901 Fixed project search field
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/create-task-page/project-search-field.tsx
Labels: bug, need test

#2969 Fixed: Cannot update attributes if a task contain at least one number attribute
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/labels-editor/label-form.tsx
Labels: bug, need test

#2971 Fixed: Incorrect text on the warning when specifying an incorrect link to the issue tracker.
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/create-task-page/create-task-content.tsx
Labels: bug

#2935 Add label check on import
  CHANGELOG.md
  cvat/apps/dataset_manager/bindings.py
  cvat/apps/engine/views.py
Labels: need test

#2871 Annotations filters new UI
  CHANGELOG.md
  cvat-core/package-lock.json
  cvat-core/package.json
  cvat-core/src/annotations-collection.js
  cvat-core/src/annotations-filter.js
  cvat-core/src/session.js
  cvat-core/tests/internal/filter.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/components/annotation-page/annotations-filters-input.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-menu.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list-header.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/states-ordering-selector.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
  cvat-ui/src/components/annotation-page/styles.scss
  cvat-ui/src/components/annotation-page/top-bar/filters-modal.tsx
  cvat-ui/src/components/annotation-page/top-bar/right-group.tsx
  cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/components/label-selector/label-selector.tsx
  cvat-ui/src/containers/annotation-page/annotation-page.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/containers/annotation-page/top-bar/filters-modal.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/icons.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/interfaces.ts
  tests/cypress/integration/actions_tasks_objects/case_13_merge_split_features.js
  tests/cypress/integration/actions_tasks_objects/case_17_lock_hide_features.js
  tests/cypress/integration/actions_tasks_objects/case_18_filters_functionality.js
  tests/cypress/integration/actions_tasks_objects/issue_1444_filter_property_shape.js
  tests/cypress/integration/actions_tasks_objects/issue_2485_navigation_empty_frames.js
  tests/cypress/integration/actions_tasks_objects/issue_2690_filters_help_window.js
Labels: enhancement

#3008 Fixed unsupported methods
  cvat-core/src/annotations-filter.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/top-bar/filters-modal.tsx
Labels: bug

#3021 Added switcher to maintain poylgon crop behaviour (#2961)
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/canvasModel.ts
  cvat-canvas/src/typescript/editHandler.ts
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/settings-actions.ts
  cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx
  cvat-ui/src/components/header/settings-modal/styles.scss
  cvat-ui/src/components/header/settings-modal/workspace-settings.tsx
  cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper.tsx
  cvat-ui/src/containers/header/settings-modal/workspace-settings.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/settings-reducer.ts
Labels: enhancement, need test

#3025 Crop polygon properly
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/cuboid.ts
  cvat-canvas/src/typescript/drawHandler.ts
  cvat-canvas/src/typescript/shared.ts
Labels: bug, need test

#3034 Updated husky to run git hooks on commit
  package-lock.json
  package.json
Labels: dependencies

#3030 Added filters and sorting options for job list, added tooltip for tasks filters
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/projects-page/search-field.tsx
  cvat-ui/src/components/search-tooltip/search-tooltip.tsx
  cvat-ui/src/components/search-tooltip/styles.scss
  cvat-ui/src/components/task-page/job-list.tsx
  cvat-ui/src/components/tasks-page/top-bar.tsx
Labels: enhancement, need test
