Repository cvat-ai/cvat, pull requests merged in 2021-02, with the labels that each got.

#2727 Fixed: Issue with point region doesn't work in Firefox
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/regionSelector.ts
Labels: bug, need test

#2733 Fixed cuboid perspective change
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/svg.patch.ts
Labels: bug

#2780 Do not call HOC component each render
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-cuboid-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-points-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polygon-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polyline-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-rectangle-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/rotate-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-control.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
Labels: bug, critical, need test

#2806 Label name editing
  cvat-core/src/labels.js
  cvat-ui/src/components/labels-editor/label-form.tsx
  cvat/apps/engine/serializers.py
Labels: need test

#2808 Fixed polygon editing
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/editHandler.ts
Labels: bug, need test

#2809 Improved maintanance of popups visibility
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/handle-popover-visibility.tsx
Labels: bug, need test

#2872 Migration to mousetrap, redesigned visualization settings
  CHANGELOG.md
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-editor.tsx
  cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/canvas/canvas-wrapper3D.tsx
  cvat-ui/src/components/annotation-page/canvas/image-setups-content.tsx
  cvat-ui/src/components/annotation-page/review-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard3D-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/styles.scss
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/shortcuts-select.tsx
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/tag-annotation-sidebar.tsx
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/header/settings-modal/player-settings.tsx
  cvat-ui/src/components/header/settings-modal/styles.scss
  cvat-ui/src/components/layout-grid/layout-grid.tsx
  cvat-ui/src/components/shortcuts-dialog/shortcuts-dialog.tsx
  cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper.tsx
  cvat-ui/src/containers/annotation-page/review-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/containers/annotation-page/standard3D-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/containers/header/settings-modal/player-settings.tsx
  cvat-ui/src/index.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/shortcuts-reducer.ts
  cvat-ui/src/utils/mousetrap-react.tsx
  tests/cypress/integration/actions_tasks_objects/case_23_canvas_grid_feature.js
  tests/cypress/integration/actions_tasks_objects/case_26_canvas_brightness_contrast_saturation_feature.js
  tests/cypress/integration/actions_tasks_objects/issue_1433_hide_functionality.js
  tests/cypress/integration/actions_tasks_objects/issue_1540_add_remove_tag.js
  tests/cypress/integration/actions_tasks_objects/issue_1882_polygon_interpolation.js
  tests/cypress/support/commands.js
Labels: bug, enhancement
