Repository cvat-ai/cvat, pull requests merged in 2021-12, with the labels that each got.

#3972 Added options to switch text font size and position
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/scss/canvas.scss
  cvat-canvas/src/typescript/canvasModel.ts
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/consts.ts
  cvat-ui/src/actions/settings-actions.ts
  cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx
  cvat-ui/src/components/header/settings-modal/styles.scss
  cvat-ui/src/components/header/settings-modal/workspace-settings.tsx
  cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper.tsx
  cvat-ui/src/containers/header/settings-modal/workspace-settings.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/settings-reducer.ts
Labels: enhancement

#4026 Fixed font-size in firefox
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/canvasView.ts
Labels: bug

#4029 Added ability to setup text labels content
  CHANGELOG.md
  cvat-canvas/package-lock.json
  cvat-canvas/package.json
  cvat-canvas/src/typescript/canvasModel.ts
  cvat-canvas/src/typescript/canvasView.ts
  cvat-canvas/src/typescript/consts.ts
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/actions/settings-actions.ts
  cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx
  cvat-ui/src/components/header/settings-modal/styles.scss
  cvat-ui/src/components/header/settings-modal/workspace-settings.tsx
  cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper.tsx
  cvat-ui/src/containers/header/settings-modal/workspace-settings.tsx
  cvat-ui/src/reducers/interfaces.ts
  cvat-ui/src/reducers/settings-reducer.ts
  tests/cypress/support/commands.js
Labels: enhancement

#3967 Fix issue: Original pdf file is deleted
  CHANGELOG.md
  cvat/apps/engine/media_extractors.py
  cvat/apps/engine/task.py
  cvat/apps/engine/tests/test_rest_api.py
Labels: bug

#4061 Fixed copy/paste for rotated shapes
  cvat-canvas/src/typescript/drawHandler.ts
  cvat-canvas/src/typescript/shared.ts
  cvat-core/package-lock.json
  cvat-core/package.json
  cvat-core/src/annotations-collection.js
  cvat-ui/package-lock.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx
  tests/cypress/integration/actions_objects/case_60_autoborder_feature.js
Labels: bug

#4080 Update documentation. Add organization section
  site/content/en/docs/manual/advanced/organization.md
  site/content/en/docs/manual/advanced/review.md
  site/content/en/docs/manual/basics/task-details.md
  site/content/en/docs/manual/basics/top-panel.md
  site/content/en/images/image194.jpg
  site/content/en/images/image197.jpg
  site/content/en/images/image233.jpg
  site/content/en/images/image234.jpg
  site/content/en/images/image235.jpg
  site/content/en/images/image236.jpg
  site/content/en/images/image237.jpg
Labels: documentation

#4024 Improved documentation site. Adding a copy button for code blocks
  README.md
  site/assets/scss/_custom.scss
  site/config.toml
  site/content/en/docs/administration/advanced/analytics.md
  site/content/en/docs/administration/advanced/backup_guide.md
  site/content/en/docs/administration/advanced/installation_automatic_annotation.md
  site/content/en/docs/administration/basics/AWS-Deployment-Guide.md
  site/content/en/docs/administration/basics/installation.md
  site/content/en/docs/contributing/development-environment.md
  site/content/en/docs/contributing/setup-additional-components.md
  site/content/en/docs/faq.md
  site/content/en/docs/manual/advanced/formats/_index.md
  site/content/en/docs/manual/advanced/formats/format-cityscapes.md
  site/content/en/docs/manual/advanced/serverless-tutorial.md
  site/content/en/docs/manual/basics/attach-cloud-storage.md
  site/content/en/docs/manual/basics/authorization.md
Labels: documentation

#4082 Update documentation (Development Environment section)
  site/content/en/docs/contributing/development-environment.md
Labels: documentation
