Repository cvat-ai/cvat, pull requests merged in 2022-11, with the labels that each got.

#5236 CVAT docs: introduction to cvat and datumaro video
  site/content/en/docs/getting_started/product_tour/cvat-intro.md
  site/content/en/docs/getting_started/product_tour/introduction-to-cvat-and-datumaro.md
Labels: documentation

#5273 Supported type for all labels
  CHANGELOG.md
  cvat-core/src/enums.ts
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-basics-edtior.tsx
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss
  cvat-ui/src/components/annotation-page/canvas/brush-tools.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/labels-list.tsx
  cvat-ui/src/components/annotation-page/standard3D-workspace/controls-side-bar/controls-side-bar.tsx
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/shortcuts-select.tsx
  cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/tag-annotation-sidebar.tsx
  cvat-ui/src/components/labels-editor/label-form.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/cvat-core-wrapper.ts
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/utils/filter-applicable-labels.ts
  cvat/apps/engine/serializers.py
  tests/cypress/integration/actions_tasks/case_72_hotkeys_change_labels.js
Labels: enhancement

#5365 Test webhooks sender: wait for delivery response
  tests/python/rest_api/test_webhooks_sender.py
Labels: tests

#5355 Implemented propagate backward
  CHANGELOG.md
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/standard-workspace/propagate-confirm.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/standard-workspace.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
  cvat-ui/src/components/annotation-page/standard3D-workspace/standard3D-workspace.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/propagate-confirm.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/index.ts
  tests/cypress/integration/actions_objects/case_53_object_propagate.js
  tests/cypress/integration/actions_tasks3/case_19_all_image_rotate_features.js
  tests/cypress/integration/issues_prs2/issue_1785_propagation_latest_frame.js
  tests/cypress/integration/masks/masks_basics.js
  tests/cypress/support/commands_organizations.js
Labels: enhancement
