Repository cvat-ai/cvat, pull requests merged in 2022-10, with the labels that each got.

#5017 Tests for Webhook sender
  cvat/apps/engine/mixins.py
  cvat/apps/engine/views.py
  cvat/apps/organizations/views.py
  cvat/apps/webhooks/models.py
  cvat/apps/webhooks/serializers.py
  tests/docker-compose.minio.yml
  tests/python/rest_api/test_webhooks.py
  tests/python/rest_api/test_webhooks_sender.py
  tests/python/shared/assets/comments.json
  tests/python/shared/assets/cvat_db/data.json
  tests/python/shared/assets/users.json
  tests/python/shared/assets/webhooks.json
  tests/python/shared/fixtures/data.py
  tests/python/shared/utils/dump_objects.py
Labels: server, tests

#5037 Enabled authentication via email
  CHANGELOG.md
  cvat-core/package.json
  cvat-core/src/common.ts
  cvat-core/src/server-proxy.ts
  cvat-ui/src/actions/auth-actions.ts
  cvat-ui/src/components/login-page/login-form.tsx
  cvat-ui/src/components/login-page/login-page.tsx
  cvat-ui/src/components/register-page/register-form.tsx
  cvat/apps/iam/serializers.py
  cvat/settings/base.py
  cvat/settings/email_settings.py
  site/content/en/docs/administration/basics/installation.md
  tests/cypress/integration/actions_users/issue_1810_login_logout.js
  tests/cypress/support/commands.js
Labels: server, ui

#5035 Add docs for webhooks
  site/content/en/docs/administration/advanced/webhooks.md
  site/content/en/images/create_organization_webhook.gif
  site/content/en/images/create_project_webhook.gif
  site/layouts/shortcodes/scroll-code.html
Labels: documentation

#5080 Added cypress tests for issue 4966
  tests/cypress/integration/actions_objects2/case_15_group_features.js
  tests/cypress/integration/actions_tasks/case_72_hotkeys_change_labels.js
  tests/cypress/support/commands.js
Labels: tests

#5098 Update setup-additional-components.md
  site/content/en/docs/contributing/setup-additional-components.md
Labels: documentation

#5124 Improve report information for Black linter
  .github/workflows/black.yml
Labels: tests

#5134 Fixed CVAT annotation view restoring
  CHANGELOG.md
  cvat-ui/package.json
  cvat-ui/src/actions/boundaries-actions.ts
Labels: bug

#5136 Update Github Actions
  .github/workflows/bandit.yml
  .github/workflows/black.yml
  .github/workflows/cache.yml
  .github/workflows/eslint.yml
  .github/workflows/full.yml
  .github/workflows/hadolint.yml
  .github/workflows/helm.yml
  .github/workflows/isort.yml
  .github/workflows/main.yml
  .github/workflows/publish_docker_images.yml
  .github/workflows/pylint.yml
  .github/workflows/remark.yml
  .github/workflows/schedule.yml
  .github/workflows/stylelint.yml
Labels: tests

#5121 CVAT docs: authorization doc updated
  site/content/en/docs/manual/basics/authorization.md
  site/content/en/images/filling_email.gif
  site/content/en/images/image001.jpg
  site/content/en/images/image003.jpg
Labels: documentation

#5123 Fix SDK tests: login once per class
  .github/workflows/main.yml
  cvat/settings/base.py
  tests/python/cli/test_cli.py
  tests/python/rest_api/test_analytics.py
  tests/python/rest_api/test_auth.py
  tests/python/rest_api/test_check_objects_integrity.py
  tests/python/rest_api/test_cloud_storages.py
  tests/python/rest_api/test_invitations.py
  tests/python/rest_api/test_issues.py
  tests/python/rest_api/test_jobs.py
  tests/python/rest_api/test_memberships.py
  tests/python/rest_api/test_organizations.py
  tests/python/rest_api/test_projects.py
  tests/python/rest_api/test_remote_url.py
  tests/python/rest_api/test_resource_import_export.py
  tests/python/rest_api/test_server.py
  tests/python/rest_api/test_tasks.py
  tests/python/rest_api/test_users.py
  tests/python/rest_api/test_webhooks.py
  tests/python/rest_api/test_webhooks_sender.py
  tests/python/sdk/fixtures.py
  tests/python/sdk/test_client.py
  tests/python/sdk/test_issues_comments.py
  tests/python/sdk/test_jobs.py
  tests/python/sdk/test_tasks.py
  tests/python/sdk/test_users.py
  tests/python/shared/fixtures/init.py
Labels: tests

#5140 [Snyk] Upgrade tus-js-client from 2.3.2 to 3.0.1
  cvat-core/package.json
  yarn.lock
Labels: dependencies

#5145 Minor improvements of z order feature
  CHANGELOG.md
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/states-ordering-selector.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/index.ts
Labels: bug, enhancement

#5154 Updated docs about some of shortcuts
  site/content/en/docs/manual/advanced/shortcuts.md
  site/content/en/docs/manual/basics/workspace.md
Labels: documentation

#5153 CVAT docs: integration/fiftyone doc
  site/content/en/docs/administration/_index.md
  site/content/en/docs/api_sdk/_index.md
  site/content/en/docs/contributing/_index.md
  site/content/en/docs/faq.md
  site/content/en/docs/integration/_index.md
  site/content/en/docs/integration/fiftyone.md
  site/content/en/docs/manual/_index.md
  site/content/en/images/fiftyone_logo.png
  site/content/en/images/image264.jpg
Labels: documentation

#5060 Refactor CI
  .github/workflows/bandit.yml
  .github/workflows/black.yml
  .github/workflows/cache.yml
  .github/workflows/comment.yml
  .github/workflows/eslint.yml
  .github/workflows/full.yml
  .github/workflows/hadolint.yml
  .github/workflows/helm.yml
  .github/workflows/isort.yml
  .github/workflows/main.yml
  .github/workflows/pylint.yml
  .github/workflows/remark.yml
  .github/workflows/schedule.yml
  .github/workflows/stylelint.yml
  .github/workflows/update-yarn-lock.yml
Labels: tests
