Repository cvat-ai/cvat, pull requests merged in 2023-09, with the labels that each got.

#6778 Fixed paddings on tasks/projects/models pages
  CHANGELOG.md
  cvat-ui/src/components/jobs-page/styles.scss
  cvat-ui/src/components/models-page/styles.scss
  cvat-ui/src/components/models-page/top-bar.tsx
  cvat-ui/src/components/projects-page/styles.scss
  cvat-ui/src/components/tasks-page/styles.scss
  cvat-ui/src/components/tasks-page/top-bar.tsx
Labels: ui/ux

#6817 Improved click handling on left sidebar
  CHANGELOG.md
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/handle-popover-visibility.tsx
Labels: ui/ux

#6771 Add gamma correction filter
  CHANGELOG.md
  cvat-canvas/.eslintrc.js
  cvat-canvas/package.json
  cvat-ui/.eslintrc.js
  cvat-ui/package.json
  cvat-ui/src/actions/settings-actions.ts
  cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx
  cvat-ui/src/components/annotation-page/canvas/views/canvas2d/gamma-filter.tsx
  cvat-ui/src/components/annotation-page/canvas/views/canvas2d/image-setups-content.tsx
  cvat-ui/src/components/annotation-page/canvas/views/canvas2d/image-setups.scss
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/reducers/settings-reducer.ts
  cvat-ui/src/utils/fabric-wrapper/fabric-wrapper.ts
  cvat-ui/src/utils/fabric-wrapper/gamma-correciton.ts
  cvat-ui/src/utils/image-processing.tsx
  cvat-ui/src/utils/opencv-wrapper/histogram-equalization.ts
  cvat-ui/src/utils/opencv-wrapper/opencv-interfaces.ts
  package.json
  tests/cypress/e2e/actions_tasks2/case_101_opencv_basic_actions.js
Labels: ui/ux

#6833 Add test for gamma correction filter
  tests/cypress/e2e/actions_tasks2/case_26_canvas_brightness_contrast_saturation_feature.js
  tests/cypress/e2e/actions_tasks2/case_26_canvas_color_settings_feature.js
Labels: tests, ui/ux

#6314 Add admin action for easy deactivation of users
  CHANGELOG.md
  cvat/apps/iam/admin.py
Labels: Easy to fix

#6828 Add test for mouseover mask/skeleton
  tests/cypress/e2e/actions_tasks2/case_111_settings_text_size_position_label_content.js
  tests/cypress/e2e/features/masks_basics.js
  tests/cypress/support/commands.js
Labels: tests, ui/ux

#6795 Data export documentation update
  site/content/en/docs/manual/advanced/formats/_index.md
  site/content/en/docs/manual/advanced/formats/coco-keypoints.md
  site/content/en/docs/manual/advanced/formats/format-camvid.md
  site/content/en/docs/manual/advanced/formats/format-cityscapes.md
  site/content/en/docs/manual/advanced/formats/format-coco.md
  site/content/en/docs/manual/advanced/formats/format-cvat.md
  site/content/en/docs/manual/advanced/formats/format-datumaro.md
  site/content/en/docs/manual/advanced/formats/format-icdar.md
  site/content/en/docs/manual/advanced/formats/format-imagenet.md
  site/content/en/docs/manual/advanced/formats/format-kitti.md
  site/content/en/docs/manual/advanced/formats/format-labelme.md
  site/content/en/docs/manual/advanced/formats/format-lfw.md
  site/content/en/docs/manual/advanced/formats/format-market1501.md
  site/content/en/docs/manual/advanced/formats/format-mot.md
  site/content/en/docs/manual/advanced/formats/format-mots.md
  site/content/en/docs/manual/advanced/formats/format-openimages.md
  site/content/en/docs/manual/advanced/formats/format-smask.md
  site/content/en/docs/manual/advanced/formats/format-tfrecord.md
  site/content/en/docs/manual/advanced/formats/format-vggface2.md
  site/content/en/docs/manual/advanced/formats/format-voc.md
  site/content/en/docs/manual/advanced/formats/format-widerface.md
  site/content/en/docs/manual/advanced/formats/format-yolo.md
  site/content/en/docs/manual/advanced/import-datasets.md
  site/content/en/images/export_job_as_dataset_dialog.png
  site/content/en/images/export_job_as_dataset_menu.png
Labels: documentation
