Repository cvat-ai/cvat, pull requests merged in 2023-05, with the labels that each got.

#6075 Fix skeleton tracks
  .github/workflows/helm.yml
  CHANGELOG.md
  cvat/apps/dataset_manager/task.py
  cvat/apps/engine/tests/test_rest_api.py
  tests/python/rest_api/test_tasks.py
  tests/python/shared/assets/cvat_db/data.json
  tests/python/shared/assets/jobs.json
  tests/python/shared/assets/labels.json
  tests/python/shared/assets/tasks.json
Labels: server

#5892 Open resource links from any organization/sandbox
  CHANGELOG.md
  cvat-core/src/api-implementation.ts
  cvat-core/src/api.ts
  cvat-core/src/common.ts
  cvat-core/src/config.ts
  cvat-core/src/organization.ts
  cvat-core/src/server-proxy.ts
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/task-page/task-page.tsx
  cvat-ui/src/components/watchers/organization-watcher.tsx
  cvat/apps/engine/models.py
  cvat/apps/engine/schema.py
  cvat/apps/engine/serializers.py
  cvat/apps/engine/view_utils.py
  cvat/apps/engine/views.py
  cvat/apps/events/handlers.py
  cvat/apps/events/serializers.py
  cvat/apps/events/views.py
  cvat/apps/iam/filters.py
  cvat/apps/iam/permissions.py
  cvat/apps/iam/schema.py
  cvat/apps/iam/views.py
  cvat/apps/lambda_manager/views.py
  cvat/apps/organizations/models.py
  cvat/apps/organizations/views.py
  cvat/apps/webhooks/views.py
  cvat/schema.yml
  cvat/settings/base.py
  tests/cypress/e2e/actions_organizations/case_113_new_organization_pipeline.js
  tests/cypress/e2e/actions_tasks/task_rectangles_only.js
  tests/cypress/e2e/skeletons/skeletons_pipeline.js
  tests/python/rest_api/test_cloud_storages.py
  tests/python/rest_api/test_issues.py
  tests/python/rest_api/test_jobs.py
  tests/python/rest_api/test_labels.py
  tests/python/rest_api/test_projects.py
  tests/python/rest_api/test_resource_import_export.py
  tests/python/rest_api/test_tasks.py
  tests/python/rest_api/utils.py
  tests/python/sdk/test_client.py
  tests/python/shared/assets/cvat_db/data.json
  tests/python/shared/assets/jobs.json
Labels: server, ui/ux

#6205 analytics documentation updated
  site/content/en/docs/administration/advanced/analytics.md
  site/content/en/docs/contributing/development-environment.md
  site/content/en/docs/manual/advanced/analytics.md
  site/content/en/images/analytic_architecture.jpg
  site/content/en/images/analytics_menu.jpg
  site/content/en/images/apply.jpg
  site/content/en/images/dashboard_00.jpg
  site/content/en/images/dashboard_01.jpg
  site/content/en/images/dashboard_02.jpg
  site/content/en/images/dashboard_03.jpg
  site/content/en/images/dashboard_04.jpg
  site/content/en/images/image096.jpg
  site/content/en/images/image097.jpg
  site/content/en/images/image113.jpg
  site/content/en/images/save_json.jpg
  site/content/en/images/save_results.jpg
  site/content/en/images/supported_events.jpg
Labels: documentation
