Repository cvat-ai/cvat, pull requests merged in 2023-10, with the labels that each got.

#6926 Try to fix unstable `case_69`
  tests/cypress/e2e/actions_tasks/registration_involved/case_69_filters_sorting_jobs.js
Labels: tests, ui/ux

#6951 Added test for manifest filetype
  cvat-ui/src/components/create-cloud-storage-page/manifests-manager.tsx
  tests/cypress/e2e/actions_tasks3/case_105_cloud_storage.js
Labels: tests, ui/ux

#6953 Persist image filters across jobs
  changelog.d/20231006_155231_persist_image_filters.md
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/canvas/views/canvas2d/gamma-filter.tsx
  cvat-ui/src/reducers/settings-reducer.ts
  cvat-ui/src/utils/fabric-wrapper/gamma-correciton.ts
Labels: enhancement, ui/ux

#6984 Fixed object states memory leak
  changelog.d/20231012_095633_klakhov_fix_memory.md
  cvat-ui/src/components/annotation-page/review/issues-aggregator.tsx
Labels: ui/ux

#6978 Added persist image filters test
  tests/cypress/e2e/actions_tasks2/case_26_canvas_color_settings_feature.js
Labels: tests, ui/ux

#6985 plan name changed to solo documentation
  site/content/en/docs/enterprise/subscription-managment.md
  site/content/en/images/bank_transfer_payment.jpg
  site/content/en/images/cancel_pro.gif
  site/content/en/images/cancel_solo.gif
  site/content/en/images/update_payment_pro.png
  site/content/en/images/update_payment_solo.png
Labels: documentation

#6901 Inviting unregistered users by email
  changelog.d/20231009_092646_invite_users.md
  cvat-core/src/api-implementation.ts
  cvat-core/src/api.ts
  cvat-core/src/organization.ts
  cvat-core/src/server-proxy.ts
  cvat-core/src/server-response-types.ts
  cvat-core/src/user.ts
  cvat-ui/src/actions/auth-actions.ts
  cvat-ui/src/actions/organization-actions.ts
  cvat-ui/src/components/accept-invitation-page/accept-invitation-page.tsx
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/organization-page/member-item.tsx
  cvat-ui/src/components/organization-page/members-list.tsx
  cvat-ui/src/components/organization-page/organization-page.tsx
  cvat-ui/src/components/register-page/register-form.tsx
  cvat-ui/src/components/register-page/register-page.tsx
  cvat-ui/src/components/signing-common/cvat-signing-input.tsx
  cvat-ui/src/components/signing-common/styles.scss
  cvat-ui/src/components/watchers/organization-watcher.tsx
  cvat-ui/src/containers/register-page/register-page.tsx
  cvat-ui/src/cvat-core-wrapper.ts
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/reducers/notifications-reducer.ts
  cvat/apps/organizations/migrations/0002_invitation_sent_date.py
  cvat/apps/organizations/models.py
  cvat/apps/organizations/serializers.py
  cvat/apps/organizations/templates/invitation/invitation_message.html
  cvat/apps/organizations/templates/invitation/invitation_subject.txt
  cvat/apps/organizations/throttle.py
  cvat/apps/organizations/views.py
  cvat/schema.yml
  cvat/settings/base.py
Labels: server, ui/ux

#7028 manual qa documentation updated
  site/content/en/docs/manual/advanced/analytics-and-monitoring/_index.md
  site/content/en/docs/manual/advanced/analytics-and-monitoring/analytics-in-cloud.md
  site/content/en/docs/manual/advanced/analytics-and-monitoring/auto-qa.md
  site/content/en/docs/manual/advanced/analytics-and-monitoring/manual-qa.md
  site/content/en/docs/manual/advanced/review.md
  site/content/en/images/image194.jpg
  site/content/en/images/image194_1.jpg
  site/content/en/images/image196_detrac.jpg
  site/content/en/images/image231.jpg
  site/content/en/images/issue_comments.png
  site/content/en/images/issue_report.jpg
  site/content/en/images/issue_report_label.jpg
  site/content/en/images/resolve_issue.jpg
  site/content/en/images/review_mode_screen.jpg
  site/content/en/images/switch_to_standart_mode.jpg
Labels: documentation

#7035 reset password procedure added to the documentation
  site/content/en/docs/manual/basics/registration.md
  site/content/en/images/change_password.jpg
  site/content/en/images/reset-password-01.jpg
  site/content/en/images/reset-password.jpg
Labels: documentation

#7070 Documentation: Need help -> Support
  site/content/en/images/change_password.jpg
  site/content/en/images/create_organization_webhook.gif
  site/content/en/images/image233.jpg
  site/content/en/images/image233_1.jpg
  site/content/en/images/image235.jpg
  site/content/en/images/personal_account.jpg
Labels: documentation

#7071 Documentation retouch: cloud storages and mot data format
  site/content/en/docs/manual/advanced/formats/format-mot.md
  site/content/en/docs/manual/basics/attach-cloud-storage.md
Labels: documentation
