Repository cvat-ai/cvat, pull requests merged in 2023-01, with the labels that each got.

#5547 Type filed description added, general task configurator update
  site/content/en/docs/manual/basics/creating_an_annotation_task.md
  site/content/en/images/attributes.jpg
  site/content/en/images/attributes_01.png
  site/content/en/images/basic_confugurator.jpg
  site/content/en/images/image005.jpg
  site/content/en/images/image124.jpg
  site/content/en/images/label_shape.gif
  site/content/en/images/label_shape.jpg
  site/content/en/images/select_files.jpg
  site/content/en/images/type_tools.png
  site/content/en/images/undefined_value.jpg
Labels: documentation

#5550 Python tests: skip the session hooks if --collect-only is used
  tests/python/shared/fixtures/init.py
Labels: sdk/cli

#5562 Images updated with delete frame icon
  site/content/en/images/cvat.jpg
  site/content/en/images/image007_detrac.jpg
  site/content/en/images/image013_detrac.jpg
  site/content/en/images/image023_affectnet.jpg
  site/content/en/images/image058_detrac.jpg
  site/content/en/images/image077_detrac.jpg
  site/content/en/images/image078_detrac.jpg
  site/content/en/images/mask_rcnn_results.jpg
Labels: documentation

#5552 YoloV7 serverless detector feature for auto annotation
  CHANGELOG.md
  README.md
  serverless/onnx/WongKinYiu/yolov7/nuclio/function-gpu.yaml
  serverless/onnx/WongKinYiu/yolov7/nuclio/function.yaml
  serverless/onnx/WongKinYiu/yolov7/nuclio/main.py
  serverless/onnx/WongKinYiu/yolov7/nuclio/model_handler.py
Labels: models

#5360 Update serverless-tutorial.md
  site/content/en/docs/manual/advanced/serverless-tutorial.md
Labels: documentation

#5444 Social account authentication tests
  .github/workflows/full.yml
  .github/workflows/main.yml
  .github/workflows/schedule.yml
  CHANGELOG.md
  cvat-core/package.json
  cvat-core/src/api-implementation.ts
  cvat-core/src/api.ts
  cvat-core/src/auth-methods.ts
  cvat-core/src/server-proxy.ts
  cvat-ui/src/actions/auth-actions.ts
  cvat-ui/src/components/login-page/login-page.tsx
  cvat-ui/src/components/login-with-social-app/login-with-social-app.tsx
  cvat-ui/src/components/signing-common/social-account-link.tsx
  cvat-ui/src/containers/login-page/login-page.tsx
  cvat-ui/src/cvat-core-wrapper.ts
  cvat-ui/src/icons.tsx
  cvat-ui/src/reducers/auth-reducer.ts
  cvat-ui/src/reducers/index.ts
  cvat/apps/engine/views.py
  cvat/apps/iam/adapters.py
  cvat/apps/iam/permissions.py
  cvat/apps/iam/rules/tests/configs/server.csv
  cvat/apps/iam/serializers.py
  cvat/apps/iam/static/social_authentication/social-github-logo.svg
  cvat/apps/iam/static/social_authentication/social-google-logo.svg
  cvat/apps/iam/urls.py
  cvat/apps/iam/views.py
  cvat/settings/base.py
  site/content/en/docs/contributing/running-tests.md
  tests/cypress/integration/actions_users/issue_1810_login_logout.js
  tests/python/social_auth/.env
  tests/python/social_auth/adapters.py
  tests/python/social_auth/docker-compose.yml
  tests/python/social_auth/server.py
  tests/python/social_auth/settings.py
Labels: tests

#5536 Add a way to create task with custom jobs
  CHANGELOG.md
  cvat-sdk/cvat_sdk/core/proxies/tasks.py
  cvat-sdk/cvat_sdk/core/uploading.py
  cvat/apps/engine/backup.py
  cvat/apps/engine/media_extractors.py
  cvat/apps/engine/models.py
  cvat/apps/engine/serializers.py
  cvat/apps/engine/task.py
  cvat/apps/engine/views.py
  tests/python/rest_api/test_tasks.py
Labels: server

#5590 Documentation for multitask updated
  site/content/en/docs/manual/basics/create-multi-tasks.md
  site/content/en/docs/manual/basics/create_an_annotation_task.md
  site/content/en/docs/manual/basics/creating-multi-tasks.md
  site/content/en/images/basic_confugurator.jpg
  site/content/en/images/image255.jpg
  site/content/en/images/image257.jpg
  site/content/en/images/image258.jpg
  site/content/en/images/image259.jpg
  site/content/en/images/image260.jpg
  site/content/en/images/image261.jpg
  site/content/en/images/multitask_configurator.png
Labels: documentation

#5059 Django social account sso
  .github/workflows/full.yml
  .github/workflows/main.yml
  cvat/apps/iam/adapters.py
  cvat/apps/iam/static/social_authentication/social-amazon-cognito-logo.svg
  cvat/apps/iam/urls.py
  cvat/apps/iam/views.py
  cvat/requirements/base.txt
  cvat/settings/base.py
  cvat/settings/development.py
  docker-compose.yml
  tests/cypress/integration/actions_users/issue_1810_login_logout.js
  tests/python/mock_oauth2/adapters.py
  tests/python/mock_oauth2/config.json
  tests/python/mock_oauth2/docker-compose.yml
  tests/python/mock_oauth2/settings.py
  tests/python/rest_api/test_auth.py
  tests/python/shared/fixtures/init.py
  tests/python/shared/utils/config.py
Labels: auth

#5622 Fix webhook signature
  CHANGELOG.md
  cvat/apps/webhooks/signals.py
  site/content/en/docs/administration/advanced/webhooks.md
Labels: documentation, server
