Repository cvat-ai/cvat, pull requests merged in 2023-11, with the labels that each got.

#7079 REST API tests for default bucket prefix
  cvat/apps/engine/cloud_provider.py
  tests/python/rest_api/test_cloud_storages.py
  tests/python/rest_api/test_tasks.py
  utils/dataset_manifest/core.py
Labels: tests

#7081 Chunk preparation optimization
  changelog.d/20231102_105602_andrey_optimization_creation_of_tasks.md
  cvat/apps/engine/cache.py
  cvat/apps/engine/media_extractors.py
  cvat/apps/engine/task.py
  cvat/apps/engine/utils.py
  cvat/settings/base.py
Labels: performance

#7074 Documentation: invite user outside of the organization
  site/content/en/docs/manual/advanced/organization.md
  site/content/en/images/invitation_to_org.jpg
  site/content/en/images/remove-resend-inv.png
Labels: documentation

#7120 Documentation: user roles updated
  site/content/en/docs/administration/advanced/iam_system_roles.md
  site/content/en/docs/manual/advanced/iam_user_roles.md
  site/content/en/images/change-stage.png
  site/content/en/images/job-stage.png
  site/content/en/images/org-roles.png
  site/content/en/images/user-roles.png
Labels: documentation

#7143 Organization workflow guide
  site/content/en/docs/getting_started/_index.md
  site/content/en/docs/getting_started/introduction-to-cvat-and-datumaro.md
  site/content/en/docs/getting_started/product_tour/_index.md
  site/content/en/docs/getting_started/product_tour/cvat-intro.md
  site/content/en/docs/getting_started/workflow-org.md
  site/content/en/images/cvat-workflow-bpmn.png
Labels: documentation

#7207 Added test for opacity reset
  tests/cypress/e2e/issues_prs/issue_7176_opacity_reset.js
Labels: tests, ui/ux
