Repository cvat-ai/cvat, pull requests merged in 2023-03, with the labels that each got.

#5780 sso documentation updated
  site/content/en/docs/administration/basics/social-accounts-configuration.md
  site/content/en/docs/enterprise/_index.md
  site/content/en/docs/enterprise/social-accounts-configuration.md
Labels: documentation

#5861 annotation with cuboids updated
  site/content/en/docs/manual/advanced/contextual-images.md
  site/content/en/docs/manual/basics/3d-object-annotation-basics.md
  site/content/en/docs/manual/basics/3d-object-annotation.md
  site/content/en/docs/manual/basics/standard-3d-mode-basics.md
  site/content/en/images/3d-canvas.jpg
  site/content/en/images/gif026_carla_town3.gif
  site/content/en/images/gif027_carla_town3.gif
  site/content/en/images/gif028_carla_town3.gif
  site/content/en/images/gif029_carla_town3.gif
  site/content/en/images/image217.jpg
Labels: documentation

#4649 Add support for Azure Blob Storage connection string authentication
  CHANGELOG.md
  cvat-core/src/cloud-storage.ts
  cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx
  cvat-ui/src/utils/enums.tsx
  cvat/apps/engine/cloud_provider.py
  cvat/apps/engine/migrations/0066_alter_cloudstorage_credentials_type.py
  cvat/apps/engine/models.py
  cvat/apps/engine/serializers.py
  cvat/schema.yml
  site/content/en/docs/manual/basics/attach-cloud-storage.md
Labels: data@cloud

#5925 Make empty previews responsive to page resize
  CHANGELOG.md
  cvat-ui/package.json
  cvat-ui/src/base.scss
  cvat-ui/src/components/cloud-storages-page/styles.scss
  cvat-ui/src/components/jobs-page/styles.scss
  cvat-ui/src/components/models-page/styles.scss
  cvat-ui/src/components/projects-page/styles.scss
  cvat-ui/src/components/task-page/styles.scss
  cvat-ui/src/components/tasks-page/styles.scss
Labels: ui/ux
