Repository cvat-ai/cvat, pull requests merged in 2024-04, with the labels that each got.

#7654 [GSoC2024] Displayed total no. of annotations
  changelog.d/20240322_004121_krishavrajsingh_Count_Annotations.md
  cvat-ui/src/components/annotation-page/single-shape-workspace/styles.scss
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/issues-list.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/labels-list.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list-header.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-side-bar.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/states-ordering-selector.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
  cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
  cvat-ui/src/components/annotation-page/styles.scss
Labels: ui/ux

#7714 Fixed annotation menu for GT objects in GT job
  changelog.d/20240402_143458_boris.md
  cvat-ui/package.json
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/reducers/annotation-reducer.ts
Labels: bug

#7729 Added support for `.rar` and some other archives
  Dockerfile
  changelog.d/20240405_091941_klakhov_rar_support.md
  cvat/apps/engine/media.mimetypes
  cvat/apps/engine/media_extractors.py
  cvat/apps/engine/tests/assets/test_rar.rar
  cvat/apps/engine/tests/test_rest_api.py
Labels: server

#7653 [GSoC2024] resolved issue #7443 (navigate over unresolved issues)
  changelog.d/20240321_205232_kavikumarceo_resolved_issue_7443.md
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/issues-list.tsx
  tests/cypress/e2e/actions_users/registration_involved/case_28_review_pipeline_feature.js
Labels: ui/ux

#7781 Fixed issue with y-slider of objects sidebar
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
Labels: ui/ux

#7739 Subscription managament documentation updated with FAQ
  site/content/en/docs/enterprise/subscription-managment.md
  site/content/en/images/add-invoice.png
  site/content/en/images/add-vat.png
  site/content/en/images/bank_transfer_payment.jpg
  site/content/en/images/bank_transfer_payment.png
  site/content/en/images/cancel-plan.png
  site/content/en/images/cancel_solo.gif
  site/content/en/images/cancel_team.gif
  site/content/en/images/change_members_number_team.gif
  site/content/en/images/invoice-icon.png
  site/content/en/images/show-invoice.png
  site/content/en/images/sm-profile-upd-inf-2.png
  site/content/en/images/sm-profile-upd-inf.png
  site/content/en/images/switch-to-annual.png
  site/content/en/images/update_payment_solo.png
  site/content/en/images/update_payment_team.png
  site/content/en/images/yearly-plan.png
Labels: documentation

#7800 refund policy updated
  site/content/en/docs/enterprise/subscription-managment.md
Labels: documentation

#7796 Fixed showing annotations at 0 frame
  changelog.d/20240423_142255_klakhov_fix_missing_annotations.md
  cvat-canvas/src/typescript/canvasModel.ts
  cvat-core/package.json
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/containers/annotation-page/annotation-page.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/index.ts
Labels: ui/ux

#7778 Added logging for `DatasetNotFound` error
  cvat/apps/dataset_manager/project.py
  cvat/apps/dataset_manager/task.py
  cvat/apps/engine/log.py
  cvat/apps/engine/utils.py
  cvat/settings/base.py
  docker-compose.yml
Labels: server
