Repository cvat-ai/cvat, pull requests merged in 2024-02, with the labels that each got.

#7348 Add the ability to disable sign-in/sign-up in the UI
  cvat-core/src/api-implementation.ts
  cvat-core/src/api.ts
  cvat-core/src/index.ts
  cvat-core/src/server-proxy.ts
  cvat-core/src/server-response-types.ts
  cvat-ui/src/actions/auth-actions.ts
  cvat-ui/src/actions/server-actions.ts
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/header/header.tsx
  cvat-ui/src/components/login-page/login-form.tsx
  cvat-ui/src/components/login-page/login-page.tsx
  cvat-ui/src/containers/login-page/login-page.tsx
  cvat-ui/src/cvat-core-wrapper.ts
  cvat-ui/src/index.tsx
  cvat-ui/src/reducers/auth-reducer.ts
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/reducers/notifications-reducer.ts
  cvat-ui/src/reducers/root-reducer.ts
  cvat-ui/src/reducers/server-api-reducer.ts
  cvat/apps/iam/urls.py
Labels: ui/ux

#7448 Run actions documentation added
  site/content/en/docs/enterprise/shapes-converter.md
  site/content/en/docs/manual/basics/top-panel.md
  site/content/en/images/image051.jpg
  site/content/en/images/run-actions-menu.jpg
  site/content/en/images/shapes-converter-annotated-dataset.jpg
  site/content/en/images/shapes-converter-dialog.jpg
  site/content/en/images/shapes-converter-setup-filter.png
  site/content/en/images/shapes-coverter-action-run.jpg
Labels: documentation

#7441 Migrate quality UI changes
  changelog.d/20240206_125854_klakhov_quality_bugfixes.md
  cvat-core/src/analytics-report.ts
  cvat-core/src/api-implementation.ts
  cvat-core/src/api.ts
  cvat-core/src/common.ts
  cvat-core/src/index.ts
  cvat-core/src/quality-conflict.ts
  cvat-core/src/quality-report.ts
  cvat-core/src/server-proxy.ts
  cvat-core/src/server-response-types.ts
  cvat-core/src/type-utils.ts
  cvat-ui/src/actions/analytics-actions.ts
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/analytics-page/analytics-page.tsx
  cvat-ui/src/components/analytics-page/analytics-performance.tsx
  cvat-ui/src/components/analytics-page/quality/common.ts
  cvat-ui/src/components/analytics-page/quality/mean-quality.tsx
  cvat-ui/src/components/analytics-page/quality/quality-settings-modal.tsx
  cvat-ui/src/components/analytics-page/quality/task-quality-component.tsx
  cvat-ui/src/components/analytics-page/shared/quality-settings-modal.tsx
  cvat-ui/src/components/analytics-page/styles.scss
  cvat-ui/src/components/analytics-page/task-quality/empty-job.tsx
  cvat-ui/src/components/analytics-page/task-quality/gt-conflicts.tsx
  cvat-ui/src/components/analytics-page/task-quality/issues.tsx
  cvat-ui/src/components/analytics-page/task-quality/job-list.tsx
  cvat-ui/src/components/analytics-page/task-quality/mean-quality.tsx
  cvat-ui/src/components/analytics-page/task-quality/quality-settings-form.tsx
  cvat-ui/src/components/analytics-page/task-quality/task-quality-component.tsx
  cvat-ui/src/components/analytics-page/utils/text-formatting.ts
  cvat-ui/src/reducers/analytics-reducer.ts
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/reducers/notifications-reducer.ts
  cvat-ui/src/reducers/root-reducer.ts
  tests/cypress/e2e/features/ground_truth_jobs.js
Labels: ui/ux

#7490 Add test for Ground truth Job list
  tests/cypress/e2e/features/ground_truth_jobs.js
Labels: tests, ui/ux

#7380 Fix bug: Fixed a problem that was overwritten and not inputted when entering Korean
  changelog.d/20240123_225942_2h-kim_hotfix_cvat_ui.md
  cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-editor.tsx
Labels: bug
