Repository cvat-ai/cvat, pull requests merged in 2024-03, with the labels that each got.

#7548 Added test for single shape annotation mode
  cvat-ui/src/components/annotation-page/single-shape-workspace/single-shape-sidebar/single-shape-sidebar.tsx
  tests/cypress/e2e/features/single_object_annotation.js
Labels: tests, ui/ux

#7621 [GSoC24] Resolved Issue #7620 (Changed the alignment of the empty component in job page)
  changelog.d/20240318_203856_kavikumarceo.md
  cvat-ui/src/components/jobs-page/jobs-page.tsx
  cvat-ui/src/components/jobs-page/styles.scss
Labels: ui/ux

#7649 Add test for check disabling button while creating gt job
  tests/cypress/e2e/features/ground_truth_jobs.js
Labels: tests, ui/ux

#7551 Move logic for downloading resources from CS into main background process
  cvat/apps/engine/backup.py
  cvat/apps/engine/cloud_provider.py
  cvat/apps/engine/utils.py
  cvat/apps/engine/views.py
  cvat/requirements/base.in
  cvat/requirements/base.txt
  cvat/requirements/development.txt
  cvat/requirements/production.txt
  cvat/rq_patching.py
  utils/dataset_manifest/requirements.txt
Labels: server

#7637 Fixed remove underlying pixels feature
  changelog.d/20240319_142812_klakhov_fix_remove_underlying_pixels.md
  cvat-ui/package.json
  cvat-ui/src/components/annotation-page/canvas/views/canvas2d/brush-tools.tsx
Labels: ui/ux

#7595 Fixed duplicated notifications for automatic annotation
  changelog.d/20240312_155103_klakhov_fix_auto_annotation_notifications.md
  cvat-core/src/lambda-manager.ts
  cvat-ui/package.json
  cvat-ui/src/actions/models-actions.ts
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/reducers/models-reducer.ts
Labels: ui/ux

#7583 [GSoC2024] fix warped image loading
  changelog.d/20240326_195957_tahamukhtar20.md
  cvat-data/src/ts/cvat-data.ts
Labels: ui/ux

#7608 Fixed sending `/events` requests from logged out users
  changelog.d/20240320_125513_klakhov_event_for_logged_out_user.md
  cvat-core/package.json
  cvat-core/src/index.ts
  cvat-core/src/logger.ts
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/utils/event-recorder.ts
Labels: ui/ux
