Repository cvat-ai/cvat, pull requests merged in 2025-02, with the labels that each got.

#8807 Save drawn shape on submit in `single shape` mode
  changelog.d/20241210_120116_klakhov_improve_single_shape_save.md
  cvat-ui/src/components/annotation-page/single-shape-workspace/single-shape-sidebar/single-shape-sidebar.tsx
  cvat-ui/src/components/annotation-page/top-bar/left-group.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/utils/drawing.ts
Labels: ui/ux

#9043 Fixed frame name text & tooltip in case of large names
  cvat-ui/src/components/annotation-page/styles.scss
Labels: ui/ux

#9095 Fix: Cannot read properties of undefined (reading 'width') in Video GT job
  changelog.d/20250212_154930_klakhov_frame_regression.md
  cvat-core/src/frames.ts
Labels: ui/ux

#9032 Added automatic saving for settings and persistent storage for image filter settings
  changelog.d/20250203_125000_klakhov_refactor_settings.md
  cvat-ui/src/actions/settings-actions.ts
  cvat-ui/src/components/header/settings-modal/settings-modal.tsx
  cvat-ui/src/utils/conflict-detector.ts
  cvat-ui/src/utils/fabric-wrapper/gamma-correciton.ts
  cvat-ui/src/utils/image-processing.tsx
  tests/cypress/e2e/actions_tasks/case_100_settings_default_number_of_points_in_polygon_approximation.js
  tests/cypress/e2e/actions_tasks/case_68_saving_settings_local_storage.js
  tests/cypress/e2e/features/shortcuts.js
  tests/cypress/support/commands.js
Labels: ui/ux

#9052 Added ability to customize logo and title
  changelog.d/20250205_141639_klakhov_setup_logo.md
  cvat-core/src/about.ts
  cvat-core/src/api-implementation.ts
  cvat-core/src/index.ts
  cvat-core/src/server-response-types.ts
  cvat-ui/src/actions/about-actions.ts
  cvat-ui/src/components/common/cvat-logo.tsx
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/header/header.tsx
  cvat-ui/src/components/header/styles.scss
  cvat-ui/src/components/signing-common/signing-layout.tsx
  cvat-ui/src/components/signing-common/styles.scss
  cvat-ui/src/cvat-core-wrapper.ts
  cvat-ui/src/icons.tsx
  cvat-ui/src/reducers/index.ts
  cvat/apps/engine/serializers.py
  cvat/apps/engine/static/logo.svg
  cvat/apps/engine/views.py
  cvat/schema.yml
  cvat/settings/base.py
Labels: server, ui/ux

#9068 [Refactoring] Refined styles for quality page
  cvat-ui/src/base.scss
  cvat-ui/src/components/quality-control/quality-control-page.tsx
  cvat-ui/src/components/quality-control/styles.scss
  cvat-ui/src/components/quality-control/task-quality/allocation-table.tsx
  cvat-ui/src/components/quality-control/task-quality/quality-magement-tab.tsx
Labels: ui/ux

#9079 fix: typos in documentation files
  cvat-canvas/src/typescript/canvasModel.ts
  site/process_sdk_docs.py
Labels: documentation

#9120 Fix more potential race conditions when fetching and enqueuing RQ jobs
  cvat/apps/lambda_manager/views.py
  cvat/apps/quality_control/quality_reports.py
Labels: server

#9124 Test autosaving of gamma correction setting
  tests/cypress/e2e/actions_tasks/case_68_saving_settings_local_storage.js
  tests/cypress/e2e/actions_tasks2/case_26_canvas_color_settings_feature.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
Labels: tests

#9126 Fix issue scaling on image filter appication
  changelog.d/20250224_103541_klakhov_fix_fit.md
  cvat-canvas/src/typescript/canvasModel.ts
Labels: ui/ux

#9082 Refactor way of working with RQ meta
  cvat/apps/consensus/merging_manager.py
  cvat/apps/consensus/views.py
  cvat/apps/dataset_manager/bindings.py
  cvat/apps/dataset_manager/project.py
  cvat/apps/dataset_manager/views.py
  cvat/apps/engine/background.py
  cvat/apps/engine/backup.py
  cvat/apps/engine/cache.py
  cvat/apps/engine/mixins.py
  cvat/apps/engine/permissions.py
  cvat/apps/engine/rq.py
  cvat/apps/engine/rq_job_handler.py
  cvat/apps/engine/serializers.py
  cvat/apps/engine/task.py
  cvat/apps/engine/utils.py
  cvat/apps/engine/views.py
  cvat/apps/events/export.py
  cvat/apps/events/handlers.py
  cvat/apps/lambda_manager/rq.py
  cvat/apps/lambda_manager/views.py
  cvat/apps/quality_control/quality_reports.py
  cvat/apps/quality_control/views.py
  pyproject.toml
Labels: server
