Repository cvat-ai/cvat, pull requests merged in 2025-01, with the labels that each got.

#8890 Allow empty items to be cached
  cvat/apps/engine/cache.py
Labels: server

#8924 Update `default-specs.js` validation params
  tests/cypress/support/default-specs.js
Labels: tests

#8804 Introduce cron jobs to clean up the export cache (`data/cache/export/`) and temporary files/directories (`data/tmp/`)
  changelog.d/20241224_150942_maria_clear_cache_cron_job.md
  cvat/apps/dataset_manager/cron.py
  cvat/apps/dataset_manager/management/__init__.py
  cvat/apps/dataset_manager/management/commands/__init__.py
  cvat/apps/dataset_manager/management/commands/cleanuplegacyexportcache.py
  cvat/apps/dataset_manager/project.py
  cvat/apps/dataset_manager/task.py
  cvat/apps/dataset_manager/tests/test_formats.py
  cvat/apps/dataset_manager/tests/test_rest_api_formats.py
  cvat/apps/dataset_manager/util.py
  cvat/apps/dataset_manager/views.py
  cvat/apps/engine/background.py
  cvat/apps/engine/backup.py
  cvat/apps/engine/management/commands/runperiodicjob.py
  cvat/apps/engine/management/commands/syncperiodicjobs.py
  cvat/apps/engine/models.py
  cvat/apps/engine/tests/test_rest_api.py
  cvat/apps/engine/tests/utils.py
  cvat/apps/engine/views.py
  cvat/settings/base.py
  cvat/settings/testing.py
  dev/format_python_code.sh
Labels: server

#8865 Improve quality UX
  changelog.d/20250114_123017_klakhov_improve_quality_ux.md
  cvat-ui/src/components/analytics-page/styles.scss
  cvat-ui/src/components/quality-control/quality-control-page.tsx
  cvat-ui/src/components/quality-control/styles.scss
  cvat-ui/src/components/quality-control/task-quality/allocation-table.tsx
  cvat-ui/src/components/quality-control/task-quality/quality-magement-tab.tsx
  cvat-ui/src/components/quality-control/task-quality/quality-table-header.tsx
  cvat-ui/src/components/quality-control/task-quality/summary.tsx
  cvat-ui/src/utils/quality.ts
  site/content/en/docs/manual/advanced/analytics-and-monitoring/auto-qa.md
  site/content/en/docs/manual/basics/quality-control.md
  site/content/en/images/honeypot05.jpg
  site/content/en/images/honeypot05.png
  site/content/en/images/quality_download_report.png
  tests/cypress/e2e/features/ground_truth_jobs.js
Labels: ui/ux

#8966 Fix: Cannot read properties of undefined (reading 'startPoints')
  changelog.d/20250120_142814_klakhov_fix_start_points.md
  cvat-canvas/src/typescript/canvasView.ts
Labels: ui/ux

#8956 Test cases for improved quality UX
  cvat-ui/src/components/quality-control/styles.scss
  cvat-ui/src/components/quality-control/task-quality/quality-table-header.tsx
  tests/cypress/e2e/features/ground_truth_jobs.js
  tests/cypress/support/commands.js
Labels: tests

#8989 Added a button to frame player to copy filename
  changelog.d/20250124_143705_klakhov_copy_frame_name_button.md
  cvat-ui/src/components/annotation-page/styles.scss
  cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
  cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/utils/to-clipboard.ts
  site/content/en/docs/manual/basics/CVAT-annotation-Interface/navbar.md
  site/content/en/images/delete_frame.jpg
  site/content/en/images/delete_frame.png
  site/content/en/images/image008.jpg
  site/content/en/images/navigation_controls.png
  site/content/en/images/navigation_icons_copy_filename.png
  site/content/en/images/navigation_icons_copy_link.png
  site/content/en/images/navigation_icons_delete_frame.png
Labels: ui/ux

#8853 Updated `Serverless tutorial` documentation
  README.md
  site/content/en/docs/getting_started/overview.md
  site/content/en/docs/manual/advanced/ai-tools.md
  site/content/en/docs/manual/advanced/automatic-annotation.md
  site/content/en/docs/manual/advanced/serverless-tutorial.md
  site/content/en/images/detectors_tab.png
  site/content/en/images/image120.jpg
  site/content/en/images/image187.jpg
  site/content/en/images/image187_1.jpg
  site/content/en/images/mask_rcnn_results.jpg
  site/content/en/images/running_automatic_annotation.png
  site/content/en/images/yolo_v3_results.jpg
  site/content/en/images/yolo_v3_results.png
Labels: documentation
