Repository cvat-ai/cvat, pull requests merged in 2025-08, with the labels that each got.

#9642 Added reposition logic into issues
  changelog.d/20250716_102252_klakhov_improve_issue_positioning.md
  cvat-canvas/src/typescript/canvas.ts
  cvat-canvas/src/typescript/canvasView.ts
  cvat-ui/src/components/annotation-page/review/create-issue-dialog.tsx
  cvat-ui/src/components/annotation-page/review/hidden-issue-label.tsx
  cvat-ui/src/components/annotation-page/review/issue-dialog.tsx
  cvat-ui/src/components/annotation-page/review/issues-aggregator.tsx
  cvat-ui/src/components/annotation-page/review/use-dialog-positioning.ts
Labels: ui/ux

#9692 Optimization: fetch previews one by one
  changelog.d/20250801_112748_klakhov.md
  cvat-ui/src/components/common/preview.tsx
  cvat-ui/src/utils/preview-queue.ts
Labels: ui/ux

#9528 Allow tasks and projects to be transferred between organizations and sandboxes
  changelog.d/20250815_112036_sekachev.bs_transfer_resource_ownership.md
  cvat-core/src/api-implementation.ts
  cvat-core/src/core-types.ts
  cvat-core/src/project-implementation.ts
  cvat-core/src/project.ts
  cvat-core/src/server-proxy.ts
  cvat-core/src/server-response-types.ts
  cvat-core/src/session-implementation.ts
  cvat-core/src/session.ts
  cvat-core/src/storage.ts
  cvat-ui/src/actions/cloud-storage-actions.ts
  cvat-ui/src/actions/organization-actions.ts
  cvat-ui/src/actions/projects-actions.ts
  cvat-ui/src/actions/tasks-actions.ts
  cvat-ui/src/components/cvat-app.tsx
  cvat-ui/src/components/header/header.tsx
  cvat-ui/src/components/header/organizations-search.tsx
  cvat-ui/src/components/header/styles.scss
  cvat-ui/src/components/projects-page/actions-menu-items.tsx
  cvat-ui/src/components/projects-page/actions-menu.tsx
  cvat-ui/src/components/select-organization-modal/select-organization-modal.tsx
  cvat-ui/src/components/selectors/organization-selector.tsx
  cvat-ui/src/components/selectors/styles.scss
  cvat-ui/src/components/tasks-page/actions-menu-items.tsx
  cvat-ui/src/components/tasks-page/actions-menu.tsx
  cvat-ui/src/components/update-linked-cs-modal/select-cs-updating-scheme-modal.tsx
  cvat-ui/src/reducers/cloud-storages-reducer.ts
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/reducers/notifications-reducer.ts
  cvat-ui/src/reducers/organizations-reducer.ts
  cvat-ui/src/utils/enums.tsx
  cvat-ui/src/utils/modals.ts
  cvat/apps/dataset_manager/tests/test_streaming_efficiency.py
  cvat/apps/engine/migrations/0093_issue_assignee_updated_date_alter_issue_assignee_and_more.py
  cvat/apps/engine/models.py
  cvat/apps/engine/permissions.py
  cvat/apps/engine/rq.py
  cvat/apps/engine/rules/projects.rego
  cvat/apps/engine/rules/tasks.rego
  cvat/apps/engine/rules/tests/configs/projects.csv
  cvat/apps/engine/rules/tests/configs/tasks.csv
  cvat/apps/engine/serializers.py
  cvat/apps/engine/tests/test_rest_api.py
  cvat/apps/engine/views.py
  cvat/apps/iam/rules/utils.rego
  cvat/apps/webhooks/signals.py
  cvat/schema.yml
  tests/python/rest_api/test_jobs.py
  tests/python/rest_api/test_projects.py
  tests/python/rest_api/test_tasks.py
  tests/python/rest_api/test_webhooks_sender.py
  tests/python/shared/assets/cvat_db/data.json
  tests/python/shared/assets/memberships.json
  tests/python/shared/assets/organizations.json
  tests/python/shared/assets/projects.json
  tests/python/shared/assets/tasks.json
  tests/python/shared/fixtures/data.py
Labels: server, ui/ux

#9768 docs: document task and project ownership transfer
  cvat-ui/src/components/update-linked-cs-modal/select-cs-updating-scheme-modal.tsx
  site/content/en/docs/manual/advanced/organization.md
  site/content/en/docs/manual/advanced/projects.md
  site/content/en/docs/manual/basics/tasks-page.md
  site/content/en/images/project_org_transfer_1.png
  site/content/en/images/project_org_transfer_2.png
  site/content/en/images/project_org_transfer_3.png
Labels: codex
