Repository cvat-ai/cvat, pull requests merged in 2025-05, with the labels that each got.

#9345 Fix 500 status code returned when an API method is not allowed
  changelog.d/20250429_101431_maria_fix_scope_defining_when_check_permissions.md
  cvat/apps/consensus/permissions.py
  cvat/apps/engine/permissions.py
  cvat/apps/events/permissions.py
  cvat/apps/iam/permissions.py
  cvat/apps/lambda_manager/permissions.py
  cvat/apps/log_viewer/permissions.py
  cvat/apps/organizations/permissions.py
  cvat/apps/quality_control/permissions.py
  cvat/apps/webhooks/permissions.py
  tests/python/rest_api/test_server.py
Labels: bug, server

#9356 Size controls for cuboid items in the 3d workspace
  changelog.d/20250430_162104_klakhov_add_cuboid_size_controls.md
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-details.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-element.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
  cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item-details.tsx
  cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
Labels: ui/ux

#9399 Added documentation for new 3D features
  site/content/en/docs/manual/advanced/3d-object-annotation-advanced.md
  site/content/en/images/cuboid_orientation.gif
  site/content/en/images/cuboid_size_input.gif
Labels: documentation

#9378 Added frame search by filename in UI
  changelog.d/20250514_171132_klakhov_frame_search.md
  cvat-ui/src/actions/annotation-actions.ts
  cvat-ui/src/components/annotation-page/annotation-page.tsx
  cvat-ui/src/components/annotation-page/styles.scss
  cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
  cvat-ui/src/components/annotation-page/top-bar/search-modal.tsx
  cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
  cvat-ui/src/reducers/annotation-reducer.ts
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/reducers/shortcuts-reducer.ts
Labels: ui/ux

#9474 Update running unit tests docs
  cvat/apps/engine/tests/test_rest_api.py
  site/content/en/docs/contributing/running-tests.md
Labels: documentation, tests, logging
