Repository cvat-ai/cvat, pull requests merged in 2025-03, with the labels that each got.

#9163 Fix a problem with frame player
  cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
Labels: ui/ux

#9151 Added search to organization page
  changelog.d/20250226_153639_klakhov_org_search.md
  cvat-core/src/organization.ts
  cvat-core/src/server-proxy.ts
  cvat-core/src/server-response-types.ts
  cvat-ui/src/components/organization-page/empty-list.tsx
  cvat-ui/src/components/organization-page/invitation-modal.tsx
  cvat-ui/src/components/organization-page/members-list.tsx
  cvat-ui/src/components/organization-page/memberships-filter-configuration.ts
  cvat-ui/src/components/organization-page/organization-page.tsx
  cvat-ui/src/components/organization-page/styles.scss
  cvat-ui/src/components/organization-page/top-bar.tsx
  cvat-ui/src/cvat-core-wrapper.ts
  cvat-ui/src/reducers/index.ts
  cvat-ui/src/utils/filter-null.ts
Labels: ui/ux

#9170 [`engine/cloud_provider.py`] Normalize function signatures
  changelog.d/20250304_174229_maria_fix_index_error.md
  cvat/apps/engine/cloud_provider.py
  cvat/apps/engine/views.py
Labels: server

#9178 Fixed styles on Consensus management page
  changelog.d/20250306_111245_klakhov_fix_consensus_management.md
  cvat-ui/src/base.scss
  cvat-ui/src/components/consensus-management-page/consensus-management-page.tsx
  cvat-ui/src/components/consensus-management-page/consensus-settings-tab.tsx
  cvat-ui/src/components/consensus-management-page/styles.scss
  cvat-ui/src/components/consensus-management-page/task-consensus/consensus-settings-form.tsx
  cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx
  cvat-ui/src/components/create-task-page/create-task-content.tsx
  cvat-ui/src/components/quality-control/quality-settings-tab.tsx
  cvat-ui/src/components/quality-control/styles.scss
  cvat-ui/src/components/quality-control/task-quality/quality-settings-form.tsx
  cvat-ui/src/utils/validation.ts
Labels: ui/ux

#9207 Updated organization documentation
  site/content/en/docs/manual/advanced/organization.md
  site/content/en/images/create_organization_form.png
  site/content/en/images/image233.jpg
  site/content/en/images/image233_1.jpg
  site/content/en/images/image234.jpg
  site/content/en/images/image235.jpg
  site/content/en/images/image236.jpg
  site/content/en/images/image237.jpg
  site/content/en/images/invitation_to_org.jpg
  site/content/en/images/invitation_to_org.png
  site/content/en/images/invitations_list.jpg
  site/content/en/images/invitations_list.png
  site/content/en/images/invite_org_members.png
  site/content/en/images/invitemembers.jpg
  site/content/en/images/org_invite_form.png
  site/content/en/images/org_members.png
  site/content/en/images/org_page.png
  site/content/en/images/org_page_steps.png
  site/content/en/images/orgpage.jpg
  site/content/en/images/personal_account.jpg
  site/content/en/images/resend-remove-invitation.jpg
  site/content/en/images/resend_remove_invitation.png
  site/content/en/images/select_org.png
  site/content/en/images/switch_org.png
  site/content/en/images/user_menu_organization.png
  site/content/en/images/user_menu_organization_create.png
  site/content/en/images/user_menu_select_org.png
Labels: documentation

#9218 Removed excessive worker config from launch
  .vscode/launch.json
Labels: server

#9039 Prevent extra tab from adding in history
  changelog.d/20250317_114443_klakhov_fix_extra_page_in_history.md
  cvat-ui/src/components/quality-control/quality-control-page.tsx
Labels: ui/ux

#9223 Improved interactor text message
  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
Labels: ui/ux

#9255 Improve actions menu
  changelog.d/20250325_154046_klakhov_improve_actions_menu.md
  cvat-ui/src/components/jobs-page/actions-menu-items.tsx
  cvat-ui/src/components/jobs-page/actions-menu.tsx
  cvat-ui/src/components/projects-page/actions-menu-items.tsx
  cvat-ui/src/components/projects-page/actions-menu.tsx
  cvat-ui/src/components/tasks-page/actions-menu-items.tsx
  cvat-ui/src/components/tasks-page/actions-menu.tsx
Labels: ui/ux

#9233 Do not reset zoom when switching between workspaces
  cvat-ui/src/components/annotation-page/canvas/grid-layout/canvas-layout.tsx
  cvat-ui/src/utils/hooks.ts
  tests/cypress/e2e/features/shortcuts.js
Labels: ui/ux
